language: go

go:
  - 1.7
  - 1.8
  - tip

script: 
  - go build
  - bash -c 'rm -f coverage.txt && go test -covermode=atomic && cat coverage.out >> coverage.txt && rm coverage.out'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false